[package]
name = "gairun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
bevy_asset_loader = "0.9.0"
bevy_kira_audio = { version = "0.8.0", features = [ "wav" ] }
bevy_asset_ron = "0.3.1"